displayName=Beep Deep
author=Cold
description=Plays some beeps when you&#39;re deep within a raid.
tags=toa,tombs,amascut,sound,sounds,audio,raid,raids,fun
version=1.0.0
plugins=com.beepdeep.BeepDeepPlugin
build=standard